### ISSUE TITLE
Add bibliography div

### ISSUE THREAD

**Issue by dmratzan** [isawnyu/smyrna-working#7]
add also the bibliography

**Comment by diyclassics** [comment]
@dmratzan Can you look at a file like [t28.1.xml](https://github.com/isawnyu/smyrna-working/blob/master/output/t28.1.xml)? It has additional bibliographic information in the <supportDesc> element. Should this be moved to the bibliography \<div\>?

**Comment by diyclassics** [comment]
@dmratzan Now looking at a file like [t9.1.xml](https://github.com/isawnyu/smyrna-working/blob/master/output/t9.1.xml)—it looks like the answer is yes. Format files like t28.1.xml the same way, correct?
